spring:
    application:
        name: lclsharding
#    datasource:
#        url: jdbc:mysql://localhost:3306/ds0?useUnicode=true&characterEncoding=utf-8&useSSL=false
#        username: root
#        password: 123456
    sharding:
        datasources:
            ds0:
                url: jdbc:mysql://localhost:3306/ds0?useUnicode=true&characterEncoding=utf-8&useSSL=false
                username: root
                password: 123456
            ds1:
                url: jdbc:mysql://localhost:3306/ds1?useUnicode=true&characterEncoding=utf-8&useSSL=false
                username: root
                password: 123456